version: "3"
services:
  db:
    image: library/postgres:12.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - skynet
  service:
    build:
      context: .
      args:
        SERVICE: data-service
    environment:
      - DATASERVICE_DB_HOST=db
      - DATASERVICE_DB_PORT=5432
      - DATASERVICE_DB_NAME=postgres
      - DATASERVICE_DB_USER=postgres
      - DATASERVICE_DB_PASSWORD=postgres
      - DATASERVICE_DB_SSLMODE=disable
    ports:
      - "8080:8080"
    networks:
      - skynet
    depends_on:
      - db
networks:
  skynet: